export const VOLUNTEER_APPLICATION_STATUSES = {
  NEW: 'NEW',
  REVIEWED: 'REVIEWED',
  ARCHIVED: 'ARCHIVED',
} as const;

export type VolunteerApplicationStatus =
  (typeof VOLUNTEER_APPLICATION_STATUSES)[keyof typeof VOLUNTEER_APPLICATION_STATUSES];

export const VOLUNTEER_APPLICATION_STATUS_VALUES = Object.values(VOLUNTEER_APPLICATION_STATUSES);
